@echo off
echo Installing NieR Automata Fishing Bot dependencies...
echo.
echo Installing pyautogui...
pip install pyautogui
echo.
echo Installing soundcard...
pip install soundcard
echo.
echo Installing numpy...
pip install numpy
echo.
echo Installation complete!
echo Press any key to exit...
pause >nul